### ISSUE TITLE
Daily Data Sync workflow errors caused by RHEL data sync

### ISSUE THREAD

**Issue by oatovar** [anchore/grype-db#254]
**Please provide a set of steps on how to reproduce the issue**

1. Trigger the `Daily Data Sync` workflow
2. Observe that the workflow fails at the `rhel provider` step.

**What happened**:

The data synced for all other providers, but failed due to the RHEL error.

**What you expected to happen**:

The sync should have completed successfully.

**Anything else we need to know?**:

Job failures:

- [2024-03-06](https://github.com/anchore/grype-db/actions/runs/8181300023)
- [2024-03-07](https://github.com/anchore/grype-db/actions/runs/8165477709)

**Environment**:
- Output of `grype-db version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by spiffcs** [comment]
Thanks @oatovar!

This PR should allow us to download the correct OVAL data even when the PULP_MANIFEST does not have an updated listing for data we pull. 

When it merges I think the plan is to kick off another db build

https://github.com/anchore/vunnel/pull/505

**Comment by willmurphyscode** [comment]
It looks like a fix for this was merged a few months ago, so I'm closing it out with `changelog-ignore` (since it fixed before the current release it doesn't belong in release notes).

Please let us know if we've missed something.
