### ISSUE TITLE
Capture the dates for the last successful pull of each vunnel provider in the grype-db metadata.json file

### ISSUE THREAD

**Issue by westonsteimel** [anchore/grype-db#255]
**What would you like to be added**:

Capture the dates of each individual providers last successful run in the grype-db metadata.json file

**Why is this needed**:

So downstream consumers of the published grypedb archive can understand how up-to-date data is for each indvidual provider

**Additional context**:
Currently any logic that needed to determine how stale vuln data is had to rely on the build date of the grype-db being the first date that any provider failed (which changes with #251 ) or needed access to the raw metadata files of the vunnel workspaces.  This will allow for anything that has access to the grypedb archive to have more fine-grained details with per-provider dates and no horrible hacks around the grypedb build date

**Comment by westonsteimel** [comment]
Fixed by https://github.com/anchore/grype-db/issues/255

**Comment by wagoodman** [comment]
I'm re-opening this since the PR that implemented this was reverted
