### ISSUE TITLE
nil dereference in file.Exists

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [anchore/grype-db#29]
[file.Exists](https://github.com/anchore/grype-db/blob/main/internal/file/exists.go#L14) checks for `IsNotExist` errors, but does not handle unexpected errors. 

I was running grype as `nobody` in a `photon` container. $HOME defaults to /dev/null, so Grype was trying to look for `/dev/null/.cache`. os.Stat returns a `not a directory` error and `os.IsNotExist(err)` returns false. `info.IsDir` is a nil dereference and grype crashes.

Two options I can think of are:
1) return false if err != nil (the file being looked for is not usable for one reason or another)
- no interface change is needed, but grype's next step might be to create that file
2) return (false, err) so grype can print the error (so the user can update configuration appropriately) and terminate

**Comment by xtreme-conor-nosal** [comment]
repro with:
```
touch /tmp/foo
XDG_CACHE_HOME=/tmp/foo grype nginx:1.16
```
output
```
⠹ Vulnerability DB        [checking for update]
 ⠹ Loading image           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ [requesting image from docker]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16c7048]

goroutine 24 [running]:
github.com/anchore/grype-db/internal/file.Exists(0x1d98a58, 0x2329a98, 0xc0002480c0, 0x21, 0x21)
	/Users/runner/go/pkg/mod/github.com/anchore/grype-db@v0.0.0-20210527140125-6f881b00e927/internal/file/exists.go:14 +0xa8
github.com/anchore/grype-db/pkg/curation.NewMetadataFromDir(0x1d98a58, 0x2329a98, 0xc000212018, 0x13, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/anchore/grype-db@v0.0.0-20210527140125-6f881b00e927/pkg/curation/metadata.go:55 +0x105
github.com/anchore/grype/grype/db.(*Curator).IsUpdateAvailable(0xc000211e08, 0x1bf5572, 0x23, 0x0, 0x0)
	/Users/runner/work/grype/grype/grype/db/curator.go:157 +0x1a5
github.com/anchore/grype/grype/db.(*Curator).Update(0xc000211e08, 0x0, 0x0, 0x0)
	/Users/runner/work/grype/grype/grype/db/curator.go:121 +0x293
github.com/anchore/grype/grype.LoadVulnerabilityDb(0xc000034738, 0x11, 0x1c0ac06, 0x3c, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/runner/work/grype/grype/grype/lib.go:35 +0x375
github.com/anchore/grype/cmd.startWorker.func1.1(0xc000574b80, 0xc0137b4680, 0xc0137b4690, 0xc00012c200, 0xc0002f9120, 0xc000100960)
	/Users/runner/work/grype/grype/cmd/root.go:208 +0x1d3
created by github.com/anchore/grype/cmd.startWorker.func1
	/Users/runner/work/grype/grype/cmd/root.go:205 +0x28b
```

**Comment by luhring** [comment]
Good catch, @xtreme-conor-nosal! I like your second approach — it seems important to bubble up this problem so that Grype can respond appropriately (in [curator.go](https://github.com/anchore/grype/blob/main/grype/db/curator.go)).

Is this fix something you're up for contributing?

**Comment by xtreme-conor-nosal** [comment]
Sure. Is Grype the only Anchore repo that would be importing grype-db?

**Comment by xtreme-conor-nosal** [comment]
I noticed grype has it's own copy of [file.Exists](https://github.com/anchore/grype/blob/main/internal/file/exists.go) but it appears to be unused
